import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <main className="flex flex-col items-center justify-center bg-[#e0f7ff]">
      <h1 className="text-3xl font-bold leading-normal mb-5">Mogy Portfolio</h1>

      <p className="text-base mb-10">
        ひとこと：ポートフォリオ、はじめました。
      </p>

      <div className="flex px-10 py-5">
        <Image
          src="/images/mogy.jpg"
          alt="mogy"
          width={200}
          height={200}
          priority
        />
        <div>
          <p className="text-xl font-bold">PROFILE</p>
          <p className="text-base">経歴とプロフィール</p>
        </div>
      </div>
    </main>
  );
};

export default Home;
